name: Godot testing

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: croconut/godot-tester@v2.5
      with:
        continue-on-error: true
        # required
        version: "3.4.4"
        # the type of release of godot that the tests should be run with
        release_type: "rc2"
        is-mono: "false"
        # the folder with your projects.godot file in it
        path: "game"
        # how long to spend importing assets before tests are run
        import-time: "5"
        # how long tests can run in seconds
        test-timeout: "45"
        # the ratio of tests that must pass for this action to pass
        # e.g. 0.6 means 60% of your tests must pass
        minimum-pass: "0.8"
        # the directory containing Gut tests
        test-dir: "res://Test/Unit"
        # default is false, set true to count asserts instead of tests
        assert-check: "true"
        # to ensure all SCRIPT ERRORs dont contribute to your failure rate
        ignore-errors: "true"
